-- Создадим таблицу Students
CREATE TABLE Students (ID INT PRIMARY KEY NOT NULL, NAME TEXT NOT NULL, START_YEAR INT NOT NULL);

--Создадим таблицу Courses 
CREATE TABLE Courses (C_NO INT PRIMARY KEY NOT NULL, TITLE TEXT NOT NULL, HOURS INT NOT NULL);

-- Создадим таблицу Exams
CREATE TABLE Exams (S_ID INT, Name_S TEXT, NO_C INT,  Name_C TEXT, SCORE INT, FOREIGN KEY (S_ID) REFERENCES Students(ID), FOREIGN KEY (NO_C) REFERENCES Courses(C_NO));